name: .NET
on:
  push:
    branches: [ "master" ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup NuGet
      uses: NuGet/setup-nuget@v1.0.5
    - name: Restore Packages
      run: nuget restore ApiMobile.sln
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --filter TestCategory=Build TestUnitaire\bin\Debug\net6.0\TestUnitaire.dll
